config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users ,only:[:edit, :index, :show, :update]
  root to: 'homes#top'
  get 'home/about'=> 'homes#about'
  
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    
    # get 'books/edit' => 'books#edit', as: 'edit_book'
    resources :book_comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
 has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  has_many :book_comments, dependent: :destroy
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
belongs_to :book
belongs_to :user
validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
 belongs_to :user
 belongs_to :book
 validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books, dependent: :destroy
   attachment :profile_image
   validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about,:public_action]
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
   book = Book.find(params[:book_id])
      comment = current_user.book_comments.new(book_comment_params)
      comment.book_id = book.id
      comment.save
      redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
      redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book=Book.new
    @user=current_user
   

  end
  def create
    @book=Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = 'successfully！'
    else
      @books=Book.all
      @user=current_user
      render :index
    end
  end
  def show
    @book = Book.find(params[:id])
    @user=@book.user
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render :edit
    else
      redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
     redirect_to book_path(@book)
      flash[:notice] = 'successfully！'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
     book.destroy
     redirect_to books_path
    flash[:notice] = 'successfully！'

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_path)

  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
   
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
   @book=Book.new
   @users=User.all
   @user=current_user
  end


  def show
   @user = User.find(params[:id])
   @books =Book.where(user_id: @user.id)
   @book = Book.new
  end

  def edit
   @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end



  end

  def update
   @user = User.find(params[:id])

    if @user.update(user_params)
     redirect_to user_path(@user)
      flash[:notice] = 'successfully！'
    else
      render :edit
    end
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_newbook.html.erb
<h1>New book</h1>
<%= form_with model: book, local: true do |form| %>

<p><%= form.label :title %><br>
<%= form.text_field :title %>

<p><%= form.label :body %><br>
<%= form.text_area :body %>
</p>

<div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
<% end %>

app/views/books/_userinfo.html.erb
<table class="table table-user">
  <h2>User info</h2>
  <thead>
    <tr>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    
  </tbody>
</table>
<div class="row">
  <%=link_to edit_user_path(user.id), class: "col-xs-12 btn btn-outline-secondary btn-block" do %>
  <span class="fas fa-user-cog"></span>
  <% end %>
</div>

app/views/books/edit.html.erb
<%= render 'books/error', model: @book%>

<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	
  	<%= form_with model:@book, local: true do |form| %>
  <div class="form-group">
    <label for="book_title">Title</label><br>
    <%= form.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label><br>
<%= form.text_area :body %>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
  </div>
<% end %>
  		<%=link_to "Show",book_path(@book.id)%> |
        <%=link_to "Back",books_path%>
  </div>
  </div>
  </div>
  </main>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/7d1cc720f9.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/userinfo', user: @user%>
    <%= render 'books/newbook', book: @book%>
    <%= render 'books/error', model: @book%>
</div>
<div class="col-md-8 offset-md-1">
  <h1>Books</h1>

<table class="table table-hober table-inverse">
  <thead>
    <tr>
      <td></td>
      <td>Title</td>
      <td>Opinion</td>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user.id) do %>
     <%= attachment_image_tag book.user, :profile_image, :fill, 40,40, fallback: "no_image.jpg" ,size:'40x40' %>
        </td><% end %>
    <td><%= link_to book.title, book_path(book.id) %></td>

        <td>
         <%= book.body%>
       </td>
        <% if  book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(book.id), method: :post do %>
        <i class="far fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </td>
  <% end %>
       <td>コメント数:<%=book.book_comments.count%></td>


        </tr>
    <%end%>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/7d1cc720f9.js" crossorigin="anonymous"></script>
<% if flash[:notice] %>
       <p class="notice">
         <%= flash[:notice]%>
       </p>
    <% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/userinfo', user: @user%>
    <%= render 'books/newbook', book: @new_book%>
    <%= render 'books/error', model: @book%>
</div>

<div class="col-md-8 offset-md-1">
 <h1>Book detail</h1>
 <table class="table table-hober table-inverse">
  <tbody>

      <tr>
       <td><%= attachment_image_tag @user, :profile_image, :fill, 40,40, fallback: "no_image.jpg" ,size:'40x40' %><br>
       <%=link_to @user.name,user_path(@user.id)%></td>
       <td><%= link_to @book.title, book_path(@book.id) %></td>
       <td><%= @book.body %></td>
       <% if @book.user_id == current_user.id %>
       <td><%= link_to "Edit", edit_book_path(@book.id) %></td>

       <td><%= link_to "Destroy", book_path(@book.id), method: :delete %></td>

       <% end %>

       <% if @book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fas fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="far fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </td>
  <% end %>
       <td>コメント数：<%= @book.book_comments.count %></td>
       </tr><br>
       
       </tbody>
  </table>
  
  <table>
      
  <tbody>
     
       <% @book.book_comments.each do |book_comment| %>
      <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40,40, fallback: "no_image.jpg" ,size:'40x40' %><br>
       <%= book_comment.user.name %>
       <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
       <% if book_comment.user == current_user %>

       <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %></td><% end %>

       <% end %>
      <td><%= form_with(model:[@book, @book_comment], local: true) do |f| %>
      <%= f.text_area :comment  %><br>
      <%= f.submit "送信" %>
      <% end %></td>



  </tbody>
  </table>

</div>
</div>
</div>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/homes/top.html.erb
<% if flash[:notice] %>
       <p class="notice">
         <%= flash[:notice]%>
       </p>
    <% end %>
<body>
    <main>
       <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div> 
    </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/7d1cc720f9.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>

     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to root_path do %><span class="text-light">Bookers</span><% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
          <li>
          <%= link_to user_path(current_user) do %><span class="fas fa-home nav-link text-light" aria-hidden="true"> Home</span>
                <% end %></li>
          <li><%= link_to users_path, class:"fas fa-users nav-link text-light" do %><span>Users</span><% end %></li>
          <li><%= link_to books_path,  class:"fas fa-book-open nav-link text-light" do %><span>Books</span><% end %></li>
          <li><%= link_to destroy_user_session_path,class:"fas fa-sign-out-alt nav-link text-light",method: :delete do %><span>logout</span><% end %></li>
        </ul>
      </div>
    </div>
  </nav>
    <% else %>
      <li><%=link_to root_path, class:"fas fa-home nav-link text-light" do %><span>Home</span><% end %></li>
      <li><%=link_to home_about_path,class:"fas fa-link nav-link text-light" do %><span>About</span><% end %></li>
      <li><%=link_to "sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light"  %></li>
      <li><%=link_to new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" do %><span>login</span><% end %></li>
    <% end %>
    </header>
     <main><%=yield %></main>
     <footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</html>

app/views/users/edit.html.erb
        <%= render 'books/error', model: @user%>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
      <%= form_with model:@user, local: true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
       <%=f.text_field:name %>
      </div>
     <div class="form-group">
        <label for="user_image">Image</label>
       <%=f.attachment_field :profile_image %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
       <%=f.text_area:introduction %>
      </div>
      
       <div class="form-group">
        <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
      </div>
      <% end %>
  </div>
</div>

      </div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/userinfo', user: @user%>
    <%= render 'books/newbook', book: @book%>
    <%= render 'books/error', model: @book%>
    </div>
   

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
      <tbody>
    <% @users.each do |user| %>
    <tr>

     <td><%= attachment_image_tag user, :profile_image, :fill, 40,40, fallback: "no_image.jpg" ,size:'40x40' %></td>

    <td><%=user.name%></td>
    <td><%=link_to"Show" ,user_path(user.id)%>
       </td>

        </tr>
    <%end%>
  </tbody>
      
    
  </table>
</div>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
       <p class="notice">
         <%= flash[:notice]%>
       </p>
    <% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/userinfo', user: @user%>
    <%= render 'books/newbook', book: @book%>
    <%= render 'books/error', model: @book%>
    </div>
   
   <div class="col-md-8 offset-md-1">
  
<h1>Books</h1>
<table class="table">
    <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
      <tbody>
    <% @books.each do |book| %>
    <tr>
     
     <td><%= link_to user_path(book.user.id) do %>
     <%= attachment_image_tag book.user, :profile_image, :fill, 40,40, fallback: "no_image.jpg" ,size:'40x40' %>
        </td><% end %>
    
    <td><%= link_to book.title ,book_path(book.id) %></td>
    <td><%=book.body %></td>
    
    <% if book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(book), method: :post do %>
        <i class="far fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </td>
  <% end %>
    <td>コメント数：<%= book.book_comments.count %></td>
    </tr>
    <%end%>
  </tbody>
      
    
  </table>
</div>
</div>
</div>


 